version: '3.9'

services:
  mp-project-database:
    image: mysql:latest
    container_name: mp_project_db
    restart: always
    environment:
      MYSQL_DATABASE: aruppi_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mp-project-data:/var/lib/mysql
    networks:
      - mp-project-network

  mp-project-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp-project-container
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: 
      DB_HOST: mp-project-database
      DB_PORT: 3306
      DB_NAME: aruppi_db
    ports:
      - "8080:8080"
    depends_on:
      - mp-project-database
    networks:
      - mp-project-network

volumes:
  mp-project-data:
    driver: local

networks:
  mp-project-network:
    driver: bridge
